name: GitHub Actions
run-name: Update README.md of Flying-Acorn/.github repository
on: [push]
jobs:
    job1:
        name: Create-Markdown-File
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5.1.1
              with:
                  python-version: '3.10'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install html2text
            - name: Generate Markdown
              run: html2text --ignore-images --single-line-break --wrap-list-items -d index.html > README.md
            - name: verify changes
              id: verify_changes
              run: |
                git diff --quiet README.md || echo "changed=true" >> $GITHUB_OUTPUT
            - name: Commit changes
              if: steps.verify_changes.outputs.changed == 'true'
              run: |
                git config --local user.email "amir@flyingacorn.studio"
                git config --local user.name "GitHub Actions"
                git add README.md
                git commit -m "Update README.md"
            - name: Push changes
              if: steps.verify_changes.outputs.changed == 'true'
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}